In [1]:
import pandas as pd

In [24]:
# Read a sample of the data
url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
df = pd.read_parquet(url)

df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [25]:
df.shape

(46912, 21)

In [26]:
df.columns = df.columns.str.lower()

In [27]:
# Check data types
df.dtypes

vendorid                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
ratecodeid                      float64
pulocationid                      int32
dolocationid                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [28]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/green_taxi')

In [29]:
print(pd.io.sql.get_schema(df, name='green_taxi', con=engine))

CREATE TABLE green_taxi (
	vendorid INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	ratecodeid FLOAT(53),
	pulocationid INTEGER,
	dolocationid INTEGER,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

to manually inspect or modify the table schema before inserting data.

In [30]:
df.head(n=0).to_sql(name='green_taxi', con=engine, if_exists='replace')

0

In [31]:
df.shape

(46912, 21)

In [32]:
df.to_sql(
        name="green_taxi",
        con=engine,
        if_exists="append")

912

In [33]:
pd.read_sql("SELECT COUNT(*) FROM green_taxi", engine)

   count
0  46912

In [ ]:
## Ran this on the terminal after to query the data
uv run pgcli -h localhost -p 5432 -u root -d green_taxi

### Zone data

In [42]:
url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"
zone_df = pd.read_csv(url)

In [43]:
zone_df.shape

(265, 4)

In [44]:
zone_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [45]:
zone_df.columns = zone_df.columns.str.lower()

In [47]:
zone_df.head(0)

Empty DataFrame
Columns: [locationid, borough, zone, service_zone]
Index: []

In [48]:
# Use the same engine as before
engine = create_engine('postgresql://root:root@localhost:5432/green_taxi')

In [49]:
zone_df.to_sql(
    name="taxi_zone_lookup",  # new table name
    con=engine,
    if_exists="replace",      # overwrite if table exists
    index=False               # don’t write the DataFrame index
)

265